[package]
name = "did-method-key"
version = "0.1.0"
authors = ["Spruce Systems, Inc."]
edition = "2018"
license = "Apache-2.0"
keywords = ["ssi", "did"]
categories = ["cryptography::cryptocurrencies"]
description = "did:key DID method, using the ssi crate"
repository = "https://github.com/spruceid/ssi/"
homepage = "https://github.com/spruceid/ssi/tree/main/did-key/"
documentation = "https://docs.rs/did-key/"

[features]
secp256k1 = ["libsecp256k1", "ssi/secp256k1", "ssi/rand"]
p256 = ["ssi/p256"]

[dependencies]
ssi = { version = "0.2", path = "../", default-features = false }
async-trait = "0.1"
thiserror = "1.0"
multibase = "0.8"
libsecp256k1 = { version = "0.3", optional = true }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.9", features = ["attributes"] }
serde_json = "1.0"
