[package]
name = "did-key"
version = "0.1.0"
authors = ["Charles E. Lehner <charles.lehner@spruceid.com>"]
edition = "2018"

[dependencies]
ssi = { path = "../", default-features = false }
async-trait = "0.1"
thiserror = "1.0"
multibase = "0.8"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.5", features = ["attributes"] }
serde_json = "1.0"
