[package]
name = "did-pkh"
version = "0.0.1"
authors = ["Spruce Systems, Inc."]
edition = "2018"

[dependencies]
ssi = { path = "../", default-features = false, features = ["secp256k1", "keccak-hash", "p256", "ripemd160"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
bs58 = { version = "0.4", features = ["check"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt"] }
