[package]
name = "did-web"
version = "0.1.0"
authors = ["Charles E. Lehner <charles.lehner@spruceid.com>"]
edition = "2018"

[dependencies]
ssi = { path = "../" }
async-trait = "0.1"
hyper = { version = "0.14", features = ["server", "client", "http1", "stream"] }
hyper-tls = "0.5"
http = "0.2"
serde_json = "1.0"
tokio = { version = "1.0", features = ["macros"] }
futures = "0.3"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
async-std = { version = "1.5", features = ["attributes"] }
