name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose --workspace

    - name: Test
      run: cargo test --verbose --workspace

    - name: Test vc-test-suite
      run: |
        cd ..
        git clone https://github.com/w3c/vc-test-suite --depth 1
        cd vc-test-suite
        npm i
        cp ../ssi/src/bin/ssi-vc-test/config.json .
        npm test
