name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build ssi
      run: cargo build --verbose

    - name: Test ssi
      run: cargo test --verbose

    - name: Test vc-test-suite
      run: |
        cd ..
        git clone https://github.com/w3c/vc-test-suite --depth 1
        cd vc-test-suite
        npm i
        cp ../ssi/src/bin/ssi-vc-test/config.json .
        npm test

    - name: Build did-resolve
      run: |
        cd did-resolve
        cargo build --verbose

    - name: Test did-resolve
      run: |
        cd did-resolve
        cargo test --verbose
