name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SSI Library
      uses: actions/checkout@v2

    - name: Cache Cargo registry and build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml', '**.rs') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose --workspace

    - name: Test
      run: cargo test --verbose --workspace

    - name: Checkout vc-test-suite
      uses: actions/checkout@v2
      with:
        repository: w3c/vc-test-suite
        path: vc-test-suite

    - name: Test vc-test-suite
      run: |
        cd vc-test-suite
        npm i
        cp ../vc-test/config.json .
        npm test
